---
- name: add tuning setting to sysctl.conf
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.ip_local_port_range = 1024 65499
      net.ipv4.tcp_tw_reuse = 1
      net.ipv4.tcp_fin_timeout = 15
      net.ipv4.tcp_syncookies=0
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
  notify: reload sysctl configure