---
- name: Password Authentication enable
  replace:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
    backup: yes

- name: Not allow Root Login directly
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin prohibit-password'
    replace: 'PermitRootLogin no'
    backup: yes
  notify: restart ssh service
