---
- name: Password Authentication and No permit Root Login
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
    backup: yes
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin prohibit-password'
    replace: 'PermitRootLogin no'
    backup: yes
  notify: restart ssh service
